Update sweetd, do not auto start dependencies

diff --git a/recipes-core/candy/sweetd/init b/recipes-core/candy/sweetd/init
--- a/recipes-core/candy/sweetd/init
+++ b/recipes-core/candy/sweetd/init
@@ -1,25 +1,9 @@
 #!/bin/sh
 
-# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
-if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
-  set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
-fi
-
-### BEGIN INIT INFO
-# Provides:          sweetd
-# Required-Start:    $all
-# Required-Stop:     $all
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Bitcoin candy dispenser daemon
-# Description:       Manages pairing and control of the Bitcoin candy dispenser
-### END INIT INFO
-
-DESC="Manages pairing and control of the Bitcoin candy dispenser"
+DESC="Manages pairing and control of the Bitcoin Candy Dispenser"
 NAME=sweetd
-DAEMON=/usr/local/bin/sweetd
+DAEMON=/usr/bin/sweetd
 DEFAULTS=/etc/default/sweetd
-PIDFILE=/var/run/sweetd.pid
 SCRIPTNAME=/etc/init.d/$NAME
 EXTRA_OPTS=
 
@@ -27,27 +11,41 @@ test -f $DAEMON || exit 0
 
 [ -s "$DEFAULTS" ] && . /etc/default/sweetd
 
-. /lib/lsb/init-functions
+. /etc/init.d/functions
+
+delay_stop() {
+	count=0
+	while [ $count -lt 9 ] ; do
+	        if pidof $DAEMON >/dev/null; then
+	                sleep 1
+	        else
+	                return 0
+	        fi
+		count=`expr $count + 1`
+	done
+	echo "Failed to stop $NAME."
+	return 1
+}
 
 case "$1" in
-start)  log_daemon_msg "Starting sweetd" "sweetd"
-        start-stop-daemon --start -b -C --oknodo --exec $DAEMON --pidfile $PIDFILE --make-pidfile -- $EXTRA_OPTS
-        log_end_msg $?
+start)  echo -n "Starting $NAME: "
+        start-stop-daemon -S -b -x $DAEMON -- $EXTRA_OPTS
+        echo "$NAME."
         ;;
-stop)   log_daemon_msg "Stopping sweetd" "sweetd"
-        start-stop-daemon --stop --oknodo --pidfile $PIDFILE --name $NAME
-        log_end_msg $?
-        rm -f $PIDFILE
+stop)   echo -n "Stopping $NAME: "
+        start-stop-daemon -K --oknodo -x $DAEMON
+        echo "$NAME."
         ;;
-restart) log_daemon_msg "Restarting sweetd" $NAME
-        $0 stop
-        $0 start
-        ;;
+restart)
+	$0 stop
+	delay_stop && $0 start
+	;;
 status)
-        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
+        status $DAEMON
+        exit $?
         ;;
-*)      log_action_msg "Usage: $SCRIPTNAME {start|stop|status|restart}"
-        exit 2
+*)      log_action_msg "Usage: $0 {start|stop|status|restart}"
+        exit 1
         ;;
 esac
 exit 0
